version: "3.8"
services:
  python-app:
    build:
      context: ./backend
    container_name: python-appplication
    ports:
      - "5000:5000"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=rootpass
      - MYSQL_DATABASE=devops_exam
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./frontend:/app/templates

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=devops_exam
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD","mysqladmin","ping","-h","localhost","-uroot","-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    
volumes:
  mysql-data:
    driver: local  
